services:
  filebrowser:
    image: filebrowser/filebrowser:latest
    container_name: clbox-filebrowser
    ports:
      - "8090:80"
    volumes:
      - ./data:/srv
      - fb_database:/database
    restart: unless-stopped

volumes:
  fb_database: